### ISSUE TITLE
plot_output issue with latest version of pandas

### ISSUE THREAD

**Issue by arabnejad** [djgroen/flee#17]
there is an issue with the latest version of pandas=1.0.1

with version `pandas = 0.25.0` there is no problem
it seems in the new version,  `DataFrame` object has no attribute `as_matrix`
we need to investigate this issue and maybe other issues related to pandas library to make sure that `flee` will work with latest version
```
$ fab localhost plot_output:mali_localhost_16,out
Traceback (most recent call last):
  File "/home/hamid/BUL/flee/plot-flee-output.py", line 410, in <module>
    :, ["refugees in camps (simulation)"]].as_matrix().flatten()
  File "/home/hamid/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

Fatal error: local() encountered an error (return code 1) while executing 'python3 ~/BUL/flee/plot-flee-output.py /home/hamid/BUL/FabSim3/results/mali_localhost_16 /home/hamid/BUL/FabSim3/results/mali_localhost_16/out'
```

**Comment by djgroen** [comment]
This has been fixed a while ago already :)
